version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/next-app"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "America/New_York"
    reviewers:
      - "RITesports/managers"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directory: "/fastify-api"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "America/New_York"
    reviewers:
      - "RITesports/managers"
    target-branch: "dev"
