version: "3.9"

services:
  server:
    image: nginx
    volumes:
      - ./nginx-server/nginx-dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
      - api

  app:
    image: node:14-alpine
    working_dir: /next-app
    command: ["npm", "run", "dev"]
    volumes:
      - ./next-app:/next-app
    depends_on:
      - api

  api:
    image: node:14-alpine
    working_dir: /fastify-api
    command: ["npm", "run", "dev"]
    environment:
      # - MONGO_USERNAME=
      # - MONGO_PASSWORD=
      - MONGO_HOST=db
      # - MONGO_PORT=
      # - MONGO_DEFAULT_AUTH_DB=
      # - MONGO_OPTIONS
    secrets:
      - cookie_private
      - jwt_public
      - jwt_private
    volumes:
      - ./fastify-api:/fastify-api
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    volumes:
      - ./mongo-db:/data/db

secrets:
  # api
  cookie_private:
    file: ./cookie_private.pem
  jwt_public:
    file: ./jwt_public.pem
  jwt_private:
    file: ./jwt_private.pem
