version: "3.9"

services:
  server:
    image: ritesports/nginx-server:main
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
      - api
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: ["/bin/sh", "-c", "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"]

  app:
    image: ritesports/next-app:main
    environment:
      - NODE_ENV=production
    depends_on:
      - api

  api:
    build: ritesports/fastify-api:main
    environment:
      - NODE_ENV=production
      # - MONGO_USERNAME=
      # - MONGO_PASSWORD=
      - MONGO_HOST=db
      # - MONGO_PORT=
      # - MONGO_DEFAULT_AUTH_DB=
      # - MONGO_OPTIONS
    secrets:
      - cookie_private
      - jwt_public
      - jwt_private
    depends_on:
      - db
  
  db:
    image: mongo
    restart: always
    volumes:
      - ./mongo-db:/data/db

secrets:
  # api
  cookie_private:
    file: ./cookie_private.pem
  jwt_public:
    file: ./jwt_public.pem
  jwt_private:
    file: ./jwt_private.pem
